# Configuration for dependency updates
version: 2

# List of dependencies to update
updates:
  # Update all Docker dependencies (if applicable)
  - package-ecosystem: "docker"
    # Package ecosystem to update (e.g., Docker)
    # Note: If no Docker ecosystem files are present in the repository, no files will be updated.
    directory: "/"
    # Directory path to search for dependencies
    schedule:
      # Update interval (e.g., daily)
      interval: "daily"
    groups:
      all-dependencies:
        patterns:
          # Pattern to match all dependencies
          - "*"

  # Update all Go dependencies (if applicable)
  - package-ecosystem: "gomod"
    # Package ecosystem to update (e.g., Go)
    # Note: If no Go ecosystem files (go.mod, go.sum) are present in the repository, no files will be updated.
    directory: "/"
    # Directory path to search for dependencies
    schedule:
      # Update interval (e.g., daily)
      interval: "daily"
    groups:
      all-dependencies:
        patterns:
          # Pattern to match all dependencies
          - "*"

  # Update all npm dependencies (if applicable)
  - package-ecosystem: "npm"
    # Package ecosystem to update (e.g., npm)
    # Note: If no npm ecosystem files (package.json, package-lock.json, yarn.lock) are present in the repository, no files will be updated.
    directory: "/"
    # Directory path to search for dependencies
    schedule:
      # Update interval (e.g., daily)
      interval: "daily"
    groups:
      all-dependencies:
        patterns:
          # Pattern to match all dependencies
          - "*"

  # Update all GitHub Actions dependencies (if applicable)
  - package-ecosystem: "github-actions"
    # Package ecosystem to update (e.g., GitHub Actions)
    # Note: If no GitHub Actions workflow files are present in the repository, no files will be updated.
    directory: "/"
    # Directory path to search for dependencies
    schedule:
      # Update interval (e.g., daily)
      interval: "daily"
    groups:
      all-dependencies:
        patterns:
          # Pattern to match all dependencies
          - "*"
