FROM i386/alpine:3.23 AS build
RUN apk add --no-cache ca-certificates

FROM scratch

ENTRYPOINT ["/usr/bin/semver-bump-action"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY bin/semver-bump-action /usr/bin/semver-bump-action
