---
name: release-notification

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  notify-on-release:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification on new release
        uses: cbrgm/telegram-github-action@23e09288be3c649591e0cd48206f44173e8a4a63 # v1.3.10
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            🚀 New Release Published!
            Release Name: ${{ github.event.release.name }}
            Tag: ${{ github.event.release.tag_name }}
            Actor: ${{ github.actor }}
            Repository: ${{ github.repository }}
            Check it out: ${{ github.event.release.html_url }}

      - name: Send Mastodon Status on new release
        id: mastodon
        uses: cbrgm/mastodon-github-action@96ff691bc465fd7654dfb68697f94465125a7e21 # v2.1.21
        if: ${{ !github.event.repository.private }}
        with:
          access-token: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          url: ${{ secrets.MASTODON_URL }}
          language: "en"
          message: |
            🚀  ${{ github.repository }} ${{ github.event.release.name }} published!
            Check it out: ${{ github.event.release.html_url }}
...
