name: Tag Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      latest_tag: ${{ steps.step1.outputs.test }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Latest Tag
        id: current
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "current version is: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Bump Minor Version
        id: bump
        uses: cbrgm/semver-bump-action@main
        with:
          current-version: ${{ steps.current.outputs.latest_tag }}
          bump-level: minor

      - name: Push Git Tag
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags --abbrev=0)
          new_tag=${{ steps.bump.outputs.next-version }}
          if [[ $(git rev-list $latest_tag..HEAD --count) -gt 0 ]]; then
            git config user.name "GitHub Actions"
            git config user.email "github-actions@users.noreply.github.com"
            git tag $new_tag
            git push origin $new_tag
          else
            echo "No new commits since last tag. Skipping tag push."
          fi
